config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users,
              # defaults:    { format: :json },
              path: "auth",
              controllers: {
                registrations: "registrations",
                passwords: "passwords",
                sessions: "sessions"
              },
              path_names: {
                sign_in: "login"
              }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Base, at: "/#{Base::PREFIX}"
  # mount Sidekiq::Web => '/sidekiq'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/auth/:provider/callback", to: "omniauth#google"
  get "/auth/failure", to: "omniauth#failure"
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "doctors#index", defaults: { tab: "root" }
  get "/test", to: "tests#test"
  get "/navbar", to: "tests#navbar"
  get "/dashboard", to: "welcome#dashboard"

  namespace :super_admin, as: :su do
    resource :dashboard, only: %i[show] do
      collection do
        get :users
        get :appointments
      end
    end

    resource :director, only: %i[] do
      collection do
        get :add_doctor
        get :add_hospital
        get :list_users
        get :appointments
        get :invitations
      end
    end
  end

  resources :appointments, only: %i[index] do
    collection do
      get ":appt_code/feedback", to: "appointments#feedback", as: :appt_feedback
    end
  end

  resources :specializations, only: %i[index] do
    member do
      get :hospitals
      get :doctors
    end
    collection do
      get :search
    end
  end

  resources :hospitals, only: %i[index show edit] do
    member do
      get :departments
      get :doctors
    end
    collection do
      get :search
    end
  end
  resources :departments, only: %i[] do
    member do
      get :doctors
    end
  end
  resources :doctors, only: %i[index show edit update] do
    collection do
      get :search
      get :availability
    end

    member do
      get :book_appointment
      get :appointments
      get :dashboard
    end
  end

  resources :patients, only: %i[index show] do
    member do
      get :appointments
    end
  end

  resources :chats, only: %i[index]

  resources :invitations, only: %i[index] do
    collection do
      get "/accept_invite/:code", to: "invitations#accept_invite", as: :accept
      post "/set_password", to: "invitations#set_password", as: :password
    end
  end

  resource :profile, only: %i[edit update]
end

app/controllers/super_admin/application_controller.rb
module SuperAdmin
  class ApplicationController < ::ApplicationController
    before_action :check_super_admin?
  end
end

app/controllers/super_admin/dashboards_controller.rb
module SuperAdmin
  class DashboardsController < ApplicationController
    def show
      mark_active_tab("dashboard")
      # @user = User.super_admin.first
    end
  end
end

app/controllers/super_admin/directors_controller.rb
module SuperAdmin
  class DirectorsController < ApplicationController
    include ListAppointments

    def add_doctor
      @hospitals = Hospital.all
    end

    def add_hospital
      @specializations = Specialization.all
    end

    def list_users
      params[:per_page] = params[:per_page] || 20

      template = ->(temp) { "super_admin/directors/list_users/#{temp}" }

      case params[:role]
      when "doctor" then set_layout(load_doctor_profiles, template["doctors"])
      when "patient" then set_layout(User, template["patients"])
      else set_layout(User.includes(:doctor_profile).where.not(id: current_user.id), template["base"])
      end
    end

    def invitations
    end
  end
end

app/views/super_admin/dashboards/appointments.html.slim
.container-fluid.mt-3
  h4 Users 
  .row
    .col-7.d-flex
      input#username.form-control placeholder="search for username"
      input#full-name.form-control placeholder="search for name"
      input#email.form-control placeholder="search for email"
      input#contact.form-control placeholder="search for contact"
    .col-4.d-flex
      select#roles.form-control
        option value=""
          | Select by Role
        - User::ROLES.each do |role|
          option value=role
            = role.humanize
      select#states.form-control
        option value=""
          | Select by account state
        - User::STATES.each do |role|
          option value=role
            = role.humanize
      select#genders.form-control
        option value=""
          | Select by gender
        - User::GENDERS.each do |gender|
          option value=gender
            = gender.humanize
    .col-1 
      button#clear-filter-button Clear Filter

  .row
    table.table.table-hover
      thead
        tr
          th scope="col" #
          th scope="col" Name 
          th scope="col" Email
          th scope="col" Username
          th scope="col" Role
          th scope="col" Contact
          th scope="col" Gender
          th scope="col" DOB
          th scope="col" Account Status
          th scope="col" Member since
      tbody
        tbody
          - User.order("role DESC, full_name ASC").each_with_index do |user, index|
            tr data-user-full-name="#{user.full_name}" data-user-email="#{user.email}" data-user-username="#{user.username}" data-user-role="#{user.role}" data-user-contact="#{user.contact}" data-user-gender="#{user.gender}" data-user-dob="#{user.date_of_birth}" data-user-state="#{user.state}"
              th = "#{index+1}"
              td = user.full_name
              td = user.email
              td = assign_NA(user.username)
              td = user.doctor? ? (link_to "#{user.role}", dashboard_doctor_path(user)) : user.role
              td = assign_NA(user.contact)
              td = user.gender
              td = user.date_of_birth
              td = user.state
              td = since_time_v1(user.created_at)

= javascript_include_tag "super_admin/dashboards/base"

app/views/super_admin/dashboards/show.html.slim
/ h1 = @user.email

.parent-box
  .admin-panel
    .links
      = link_to "List Hospitals", hospitals_path, class: "link-path"
      = link_to "List All Drs", list_users_su_director_path(role: "doctor"), class: "link-path"
      = link_to "Add new Dr", add_doctor_su_director_path(role: "doctor"), class: "link-path"
      = link_to "Add new Hospital", add_hospital_su_director_path, class: "link-path"
      = link_to "List All Patients", list_users_su_director_path(role: "patient"), class: "link-path"
      = link_to "List All Users", list_users_su_director_path, class: "link-path"
      = link_to "Invitations", invitations_path, class: "link-path"
      / = link_to "Invitations", invitations_su_director_path, class: "link-path"