config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users,
              # defaults:    { format: :json },
              path: "auth",
              controllers: {
                registrations: "registrations",
                passwords: "passwords",
                sessions: "sessions"
              },
              path_names: {
                sign_in: "login"
              }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Base, at: "/#{Base::PREFIX}"
  # mount Sidekiq::Web => '/sidekiq'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/auth/:provider/callback", to: "omniauth#google"
  get "/auth/failure", to: "omniauth#failure"
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "doctors#index", defaults: { tab: "root" }
  get "/test", to: "tests#test"
  get "/navbar", to: "tests#navbar"
  get "/dashboard", to: "welcome#dashboard"

  namespace :super_admin, as: :su do
    resource :dashboard, only: %i[show] do
      collection do
        get :users
        get :appointments
      end
    end

    resource :director, only: %i[] do
      collection do
        get :add_doctor
        get :add_hospital
        get :list_users
        get :appointments
        get :invitations
      end
    end
  end

  resources :appointments, only: %i[index] do
    collection do
      get ":appt_code/feedback", to: "appointments#feedback", as: :appt_feedback
    end
  end

  resources :specializations, only: %i[index] do
    member do
      get :hospitals
      get :doctors
    end
    collection do
      get :search
    end
  end

  resources :hospitals, only: %i[index show edit] do
    member do
      get :departments
      get :doctors
    end
    collection do
      get :search
    end
  end
  resources :departments, only: %i[] do
    member do
      get :doctors
    end
  end
  resources :doctors, only: %i[index show edit update] do
    collection do
      get :search
      get :availability
    end

    member do
      get :book_appointment
      get :appointments
      get :dashboard
    end
  end

  resources :patients, only: %i[index show] do
    member do
      get :appointments
    end
  end

  resources :chats, only: %i[index]

  resources :invitations, only: %i[index] do
    collection do
      get "/accept_invite/:code", to: "invitations#accept_invite", as: :accept
      post "/set_password", to: "invitations#set_password", as: :password
    end
  end

  resource :profile, only: %i[edit update]
end

app/controllers/super_admin/directors_controller.rb
module SuperAdmin
  class DirectorsController < ApplicationController
    include ListAppointments

    def add_doctor
      @hospitals = Hospital.all
    end

    def add_hospital
      @specializations = Specialization.all
    end

    def list_users
      params[:per_page] = params[:per_page] || 20

      template = ->(temp) { "super_admin/directors/list_users/#{temp}" }

      case params[:role]
      when "doctor" then set_layout(load_doctor_profiles, template["doctors"])
      when "patient" then set_layout(User, template["patients"])
      else set_layout(User.includes(:doctor_profile).where.not(id: current_user.id), template["base"])
      end
    end

    def invitations
    end
  end
end

app/views/super_admin/directors/list_users/_account_status.slim
td  
  - if user.active?
    .btn.btn-warning data-user-id="#{user.id}" data-user-change-state="#{user.state}"
      | suspend
  - else 
    .btn.btn-success data-user-id="#{user.id}" data-user-change-state="#{user.state}"
      | activate

app/views/super_admin/directors/list_users/base.html.slim
.container-fluid.mt-3
  h4 Users 
  .row
    .col-7.d-flex
      input#username.form-control placeholder="search for username"
      input#full-name.form-control placeholder="search for name"
      input#email.form-control placeholder="search for email"
      input#contact.form-control placeholder="search for contact"
    .col-2.d-flex
      select#genders.form-control
        option value=""
          | Select by gender
        - User::GENDERS.each do |gender|
          option value=gender
            = gender.humanize
    .col-1 
      button#clear-filter-button.default-btn Clear Filter

  .row
    table.table.table-hover
      thead
        tr
          th scope="col" #
          th scope="col" Name 
          th scope="col" Email
          th scope="col" Username
          th scope="col" Role
          th scope="col" Contact
          th scope="col" Gender
          th scope="col" DOB
          th scope="col" Account Status
          th scope="col" Member since
      tbody
        tbody
          - @users.each_with_index do |user, index|
            tr data-user-full-name="#{user.full_name}" data-user-email="#{user.email}" data-user-username="#{user.username}" data-user-role="#{user.role}" data-user-contact="#{user.contact}" data-user-gender="#{user.gender}" data-user-dob="#{user.date_of_birth}" data-user-state="#{user.state}"
              th = "#{index+1}"
              td = user.full_name
              td = user.email
              td = assign_NA(user.username)
              td = user.doctor? ? (link_to "#{user.role}", dashboard_doctor_path(user.doctor_profile), class: "a-2-btn") : (link_to "#{user.role}", patient_path(user), class: "a-2-btn")
              td = assign_NA(user.contact)
              / td = capitalize(user.gender[0])
              td = try(:capitalize, user.try(:gender)).try(:first) || "N/A"
              td = user.date_of_birth
              = render partial: "/super_admin/directors/list_users/account_status", locals: {user: user}
              td = since_time_v1(user.created_at)

= render partial: "shared/pagination", locals: { resource: @users } 

= javascript_include_tag "super_admin/dashboards/base"
= javascript_include_tag "super_admin/directors/list_users/account_status", type: :module

app/views/super_admin/directors/list_users/doctors.html.slim
.container.mt-3
  h4 Doctors
  .row
    table.table.table-hover
      thead
        tr
          th scope="col" Name 
          th scope="col" Gender
          th scope="col" DOB
          th scope="col" Hospital
          th scope="col" Specialization
          th scope="col" Start At
          th scope="col" End At
          th scope="col" Slot Interval
          th scope="col" Years of Exp
          th scope="col" Qualification
          th scope="col" Profile
          th scope="col" Edit
      tbody
        tbody
          - @users.each do |doctor, index|
            tr 
              td = doctor.doctor_name
              td = doctor.gender
              td = doctor.dob
              td.overflow-control = doctor.hospital_name
              td.overflow-control = doctor.spec_name
              td = doctor.start_at
              td = doctor.end_at
              td = "#{doctor.slot_duration} min"
              td = "#{doctor.experience_time} years"
              td = doctor.highest_qualification
              td = link_to "Dr Profile", dashboard_doctor_path(doctor), class: "a-2-btn"
              td = link_to "Edit", edit_doctor_path(doctor), class: "a-2-btn"

= render partial: "shared/pagination", locals: {resource: @users}

app/views/super_admin/directors/list_users/patients.html.slim
.container.mt-3
  h4 Patients
  .row
    .col-9
      table.table.table-hover
        thead
          tr
            th scope="col" Name 
            th scope="col" Gender
            th scope="col" DOB
            th scope="col" Profile
            th scope="col" Status
        tbody
          tbody
            - @users.each do |patient|
              tr 
                td = patient.full_name
                td = patient.gender
                td = patient.date_of_birth
                td = link_to "Visit", patient_path(patient), class: "a-2-btn"
                   
                td = patient.state

= render partial: "shared/pagination", locals: {resource: @users}