config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users,
              # defaults:    { format: :json },
              path: "auth",
              controllers: {
                registrations: "registrations",
                passwords: "passwords",
                sessions: "sessions"
              },
              path_names: {
                sign_in: "login"
              }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Base, at: "/#{Base::PREFIX}"
  # mount Sidekiq::Web => '/sidekiq'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/auth/:provider/callback", to: "omniauth#google"
  get "/auth/failure", to: "omniauth#failure"
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "doctors#index", defaults: { tab: "root" }
  get "/test", to: "tests#test"
  get "/navbar", to: "tests#navbar"
  get "/dashboard", to: "welcome#dashboard"

  namespace :super_admin, as: :su do
    resource :dashboard, only: %i[show] do
      collection do
        get :users
        get :appointments
      end
    end

    resource :director, only: %i[] do
      collection do
        get :add_doctor
        get :add_hospital
        get :list_users
        get :appointments
        get :invitations
      end
    end
  end

  resources :appointments, only: %i[index] do
    collection do
      get ":appt_code/feedback", to: "appointments#feedback", as: :appt_feedback
    end
  end

  resources :specializations, only: %i[index] do
    member do
      get :hospitals
      get :doctors
    end
    collection do
      get :search
    end
  end

  resources :hospitals, only: %i[index show edit] do
    member do
      get :departments
      get :doctors
    end
    collection do
      get :search
    end
  end
  resources :departments, only: %i[] do
    member do
      get :doctors
    end
  end
  resources :doctors, only: %i[index show edit update] do
    collection do
      get :search
      get :availability
    end

    member do
      get :book_appointment
      get :appointments
      get :dashboard
    end
  end

  resources :patients, only: %i[index show] do
    member do
      get :appointments
    end
  end

  resources :chats, only: %i[index]

  resources :invitations, only: %i[index] do
    collection do
      get "/accept_invite/:code", to: "invitations#accept_invite", as: :accept
      post "/set_password", to: "invitations#set_password", as: :password
    end
  end

  resource :profile, only: %i[edit update]
end

app/models/specialization.rb
class Specialization < ApplicationRecord
  has_many :departments
  has_many :hospitals, through: :departments
  has_many :doctor_profiles, through: :departments

  validates :name, presence: true, uniqueness: true, length: { minimum: 8, maximum: 35 }
end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
  include DoctorCount
  set_user_access :is_support_user?

  def index
    mark_active_tab("specializations")
    @hosp_count = Hospital.joins(:departments).group("departments.specialization_id").count
    @dr_count = DoctorProfile.joins(:department).group("departments.specialization_id").count

    if current_user&.doctor?
      @dr_count = DoctorProfile.joins(:department).where("departments.hospital_id = ?", current_user.doctor_profile.department.hospital_id).group("departments.specialization_id").count
    end
    if params[:without_dr] == "false"
      @specializations = scope.list.joins(departments: :doctor_profiles)
    else
      @specializations = scope.list
    end

    @specializations = @specializations.order(:name).paginate(will_paginate)
  end

  def hospitals
    @dr_count = hospital_dr_count
    @hospitals = Hospital.includes(:departments).where(departments: { specialization_id: params[:id] }).paginate(will_paginate)

    render template: "hospitals/index"
  end

  def doctors
    doc_scope = DoctorsScope.new(current_user)
    @doctors = doc_scope.list.where(specializations: { id: params[:id] })

    render template: "hospitals/doctors"
  end

  def search
    @specializations = Specialization.where("name ILIKE ?", "%#{params[:query]}%").paginate(pagination(10))
    render template: "specializations/index"
  end

  def scope
    @scope ||= SpecializationsScope.new(current_user)
  end
end

app/views/specializations/index.html.slim
.container 
  .row.m-3
    .col-3
      input#specialization-search-field.form-control type="text" placeholder="name of specialization"
    .col-1
      #reset-filter-button.btn.btn-secondary Reset
    .col-1
      #search-button.btn.btn.btn-primary Search
    = render partial: "shared/dropdown_filters", locals: {links: [["Hide Specializations with 0 Dr", specializations_path(without_dr: false)]]}
    / .col-1.dropdown-opts-container 
    /   .filter-btn Filter
    /   .hide-dropdown
    /   .dropdown-options 
    /     .links 
    /       = link_to "Hide Specializations with 0 Dr", specializations_path(without_dr: false)

  .row 
    .col-8
      - if @specializations.present?
        table.table
          thead
            tr
              th scope="col" #
              th scope="col" Name
              - unless is_doctor?
                th scope="col" Hospitals
              th scope="col" Doctors
          tbody#doctor-appointments-table-body
            - @specializations.each_with_index do |specialization, index|
              tr data-specialization-name="#{specialization.name}"
                td = "#{index+1}"
                td = specialization.name
                - unless is_doctor?
                  td 
                    / = link_to "Get List", hospitals_specialization_path(specialization), class: "a-2-btn min-width-50px"
                    = link_to "#{hospital_count(@hosp_count.try(:dig, specialization.id))}", hospitals_specialization_path(specialization), class: "a-2-btn min-width-85px"
                td 
                  / = link_to "Get List", doctors_specialization_path(specialization), class: "a-2-btn"
                  = link_to "#{doctor_count(@dr_count.try(:dig, specialization.id))}", doctors_specialization_path(specialization), class: "a-2-btn"
  
        = render_pagination(@specializations)
      - else 
        h4.no-doc-avail No Specialization Found
= render partial: "shared/spinner", locals: {dom_id: "search-button"}

= javascript_include_tag "specializations/index", type: :module