config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users,
              # defaults:    { format: :json },
              path: "auth",
              controllers: {
                registrations: "registrations",
                passwords: "passwords",
                sessions: "sessions"
              },
              path_names: {
                sign_in: "login"
              }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Base, at: "/#{Base::PREFIX}"
  # mount Sidekiq::Web => '/sidekiq'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/auth/:provider/callback", to: "omniauth#google"
  get "/auth/failure", to: "omniauth#failure"
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "doctors#index", defaults: { tab: "root" }
  get "/test", to: "tests#test"
  get "/navbar", to: "tests#navbar"
  get "/dashboard", to: "welcome#dashboard"

  namespace :super_admin, as: :su do
    resource :dashboard, only: %i[show] do
      collection do
        get :users
        get :appointments
      end
    end

    resource :director, only: %i[] do
      collection do
        get :add_doctor
        get :add_hospital
        get :list_users
        get :appointments
        get :invitations
      end
    end
  end

  resources :appointments, only: %i[index] do
    collection do
      get ":appt_code/feedback", to: "appointments#feedback", as: :appt_feedback
    end
  end

  resources :specializations, only: %i[index] do
    member do
      get :hospitals
      get :doctors
    end
    collection do
      get :search
    end
  end

  resources :hospitals, only: %i[index show edit] do
    member do
      get :departments
      get :doctors
    end
    collection do
      get :search
    end
  end
  resources :departments, only: %i[] do
    member do
      get :doctors
    end
  end
  resources :doctors, only: %i[index show edit update] do
    collection do
      get :search
      get :availability
    end

    member do
      get :book_appointment
      get :appointments
      get :dashboard
    end
  end

  resources :patients, only: %i[index show] do
    member do
      get :appointments
    end
  end

  resources :chats, only: %i[index]

  resources :invitations, only: %i[index] do
    collection do
      get "/accept_invite/:code", to: "invitations#accept_invite", as: :accept
      post "/set_password", to: "invitations#set_password", as: :password
    end
  end

  resource :profile, only: %i[edit update]
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  EXPIRE_AFTER = 2.hours

  belongs_to :referrer, class_name: "User"
  belongs_to :recipient, class_name: "User", optional: true

  enum invitee_role:  [ :patient, :doctor, :admin, :super_admin, :support ]
  enum status: %i[sent accepted revoked registered expired]

  validates :email,
            presence: true,
            # uniqueness: { message: "already has an invite" },
            format: { with: /\A[^@]+@[^@]+\.[^@]+\z/, message: "doesn't have valid format" }
  # validate :custom_validations, on: :create

  after_initialize -> {
    self.invite_code ||= SecureRandom.hex(20)
    self.status ||= :sent
    self.valid_till ||= Time.now + EXPIRE_AFTER
  }

  def is_valid_invitation?
    valid_till > Time.now
  end

  def build_support_user(**opts)
    send(:build_recipient, { role: :support }.merge(opts))
  end

  private

  # def custom_validations
  #   if User.find_by(email: email)
  #     errors.add(:base, "Email already assosiated with registered user")
  #   end
  # end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :validate_invitation, only: %i[accept_invite]
  before_action :check_super_admin?, only: %i[index]

  def index
    @invitations = Invitation.includes(:referrer)
    @invitations = @invitations.where("email ILIKE ?", "%#{params[:query]}%") if params[:query]
    @invitations = case params[:status]
    when "sent" then @invitations.sent
    when "accepted" then @invitations.accepted
    when "revoked" then @invitations.revoked
    when "registered" then @invitations.registered
    when "expired" then @invitations.expired
    else
                      @invitations
    end
                    .order(created_at: :desc)
                    .paginate(will_paginate)
  end

  def accept_invite
    if params[:accepted] == "false" && @invitation.sent?
      @invitation.revoked!
      redirect_to root_path, notice: "Invitation has been revoked"
    else
      user, message = User.create_user_without_validation(email: @invitation.email, role: "support")

      if user.present?
        warden.set_user(user)
        @invitation.update_column(:recipient_id, user.id)
        @invitation.registered!
        redirect_to edit_profile_path, notice: "Complete your profile"
      else
        redirect_to root_path, notice: message
      end

    end
  end

  private

  def set_invitation
    @invitation ||= Invitation.find_by(invite_code: params[:code])
  end

  def validate_invitation
    invite = set_invitation

    if current_user && current_user == invite.recipient
      redirect_to edit_profile_path
      return
    end

    begin
      raise "Invalid Invitation code" unless invite

      raise "User has already sign up with this invitation" if invite.registered?

      raise "Invitation has been expired" if invite.expired? || !invite.is_valid_invitation?

      raise "Invitation has been revoked by the invitee" if invite.revoked?

      invite
    rescue => e
      redirect_to root_path, notice: e.message
    end
  end
end

app/helpers/invitation_helper.rb
module InvitationHelper
  def inv_referrer(ref)
    current_user && current_user == ref ? "You" : ref.full_name
  end
end

app/views/invitations/accept_invite.html.slim
h3 Set Password 

/ = form_with scope: :password, url: "/api/v1/users/invitation/#{params[:code]}/set_password" do |f|
= form_with scope: nil, url: password_invitations_path(code: params[:code]) do |f|
  .f-field 
    = f.label :password
    = f.password_field :password, class: "pwd"

  .f-field 
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: "pwd-confirm"

  .f-field
    = f.submit "Set Password", class: "set-pwd"

= javascript_include_tag "invitations/accept_invite", type: :module

app/views/invitations/index.html.slim
.invite-list-m-container
  .new-invite-box
    = link_to "Invite", invitations_su_director_path, class: "new-invite-a"

  .invite-status-container 
    = link_to "All", invitations_path, class: "invite-status"
    - Invitation.statuses.keys.each do |status| 
      = link_to "#{status.capitalize}", invitations_path(status: status), class: "invite-status"
  
  .invite-filters
    input.search-invited-user[type="text" placeholder="Invited user mail"]
    button.search-invited-user-btn Search
  .invite-list-table-container 
    .invitations-table
      table 
        thead 
          tr 
            th Email 
            th Sent At 
            th Since
            th Status
            / th Invite Code
            th Refferer 
        tbody 
          - @invitations.each do |invite|
            tr 
              td = invite.email 
              td = am_pm_notation(invite.created_at.in_time_zone("Asia/Kolkata")) 
              td = since_time_v1(invite.created_at)
              td = invite.status
              / td = invite.invite_code
              / td = invite.referrer.full_name
              td = inv_referrer(invite.referrer)
  = render partial: "shared/pagination", locals: {resource: @invitations}

= javascript_include_tag "invitations/index", type: :module